### ISSUE TITLE
Add code_of_conduct.md

### ISSUE THREAD

**Issue by kartikey369-ind** [this-is-yaash/sneaky-package#37]
I want to add code_of_conduct.md to our repository

**Comment by jindalpriyanshu101** [comment]
Assigned @kartikey369-ind, you're good to go.

**Comment by kartikey369-ind** [comment]
If possible can you add hacktoberfest as iam participating even in that

**Comment by kartikey369-ind** [comment]
done my work https://github.com/this-is-yaash/sneaky-package/pull/39
