### ISSUE TITLE
File Not Found error not handled

### ISSUE THREAD

**Issue by tannuiscoding** [this-is-yaash/sneaky-package#42]
clipboard command fails if the file does not exist. it is not handled in the code in graph.py

**Comment by this-is-yaash** [comment]
Someone is already working on this issue. Thank you for showing interest in this project! Please take some time to explore and learn more about how this project works, and feel free to raise your own issue.

Alternatively, you can keep an eye on the Issues section and request to have that issue assigned to you if it becomes available.
